### ISSUE TITLE
entrypoint.php does not return a non-zero exit code on failure (e.g. auth error)

### ISSUE THREAD

**Issue by yoriiis** [danharrin/monorepo-split-github-action#58]
### Describe the bug

The current `entrypoint.php` script does not return a non-zero exit code when a failure occurs internally (such as a Git authentication error, failed `chdir`, or missing `.git` directory). This leads to CI jobs (e.g., GitHub Actions, GitLab CI) reporting success even when the monorepo split clearly failed.

### Steps to reproduce

1. Run the splitter with an invalid Git token (e.g., incorrect or missing token in environment variable).
2. Observe that `git clone` fails and errors like `Authentication failed` or `No such file or directory` appear.
3. Despite the failure, the script finishes and returns a `0` exit code.
4. The CI job incorrectly reports success.

### Example output

Here is a real-world log extract (GitLab CI), using an intentionally invalid token to simulate an auth error:

<pre>
$ php /splitter/entrypoint.php
[NOTE] Resolving configuration...
[NOTE] Cloning "https://gitlab.com/company/project-path.git" repository to "/tmp/monorepo_split/clone_directory" directory
[NOTE] Running: git clone -- https://oauth2:[MASKED]@gitlab.com/company/project-path.git /tmp/monorepo_split/clone_directory
Cloning into '/tmp/monorepo_split/clone_directory'...
remote: HTTP Basic: Access denied. If a password was provided for Git authentication, the password was incorrect or you're required to use a token instead of a password. If a token was provided, it was either incorrect, expired, or improperly scoped. See https://gitlab.com/help/topics/git/troubleshooting_git.md#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for 'https://gitlab.com/company/project-path.git/'
Warning: chdir(): No such file or directory (errno 2) in /splitter/entrypoint.php on line 39
[NOTE] Trying to checkout main branch
Switched to a new branch 'main'
[NOTE] Cleaning destination repository of old files
cp: can't stat '/tmp/monorepo_split/clone_directory/.git': No such file or directory
Command failed
Cleaning up project directory and file based variables
00:02
Job succeeded
</pre>

Despite multiple errors (`Authentication failed`, `chdir(): No such file`, `cp: can't stat`), the script finishes with a success status, causing the CI job to **incorrectly report success**.

### Expected behavior

The script should:
- Return a **non-zero** exit code when an internal command fails.
- Fail fast when a `git clone`, file operation, or directory change fails.

### Why it matters

This breaks reliability in CI/CD workflows. Downstream tasks may proceed under the false assumption that the split operation succeeded, potentially propagating incorrect states or triggering deployments.

### Related

- This issue is a regression from [PR #38](https://github.com/danharrin/monorepo-split-github-action/pull/38), which added proper exit handling but was reverted without further discussion.
- Comment: https://github.com/danharrin/monorepo-split-github-action/pull/38#issuecomment-2066710893

### Proposed solution

Reintroduce exit code handling with `exit(1)` (or appropriate non-zero codes) when:
- `git clone` or other shell commands fail (e.g., using `proc_open` or checking return values)
- Exceptions are thrown or fatal conditions are encountered
- Any operation that makes the split incomplete or invalid

**Comment by danharrin** [comment]
I think this is resolved by #48

**Comment by yoriiis** [comment]
@danharrin The issue has not been resolved. I tested with the latest version and still get the same error. Could you please test it on your end?

**Comment by danharrin** [comment]
Would you mind maybe attempting a PR to fix it?

**Comment by yoriiis** [comment]
> Would you mind maybe attempting a PR to fix it?

Yes, I'll run some tests and get back to you

**Comment by yoriiis** [comment]
@danharrin I get the error with the official image. But, if I build the image from the source code on the main branch and test with that image, I no longer get an error.

This seems to indicate that the image (on Docker Hub) is not up to date with the latest changes on the main branch.

On Docker Hub, the image was updated 3 years ago
<img width="576" height="651" alt="Image" src="https://github.com/user-attachments/assets/a3797f71-4b14-4ac7-af18-97350e351c2c" />

See https://hub.docker.com/r/symplify2/monorepo-split/tags

**Comment by danharrin** [comment]
Is your workflow using `uses: danharrin/monorepo-split-github-action@v2.4.0`? The Docker image in your screenshot is owned by the previous owner and I do not have access to update it.

This is how I use the current version: https://github.com/filamentphp/filament/blob/b4f9bff4f0d4d52390de56982f73a06c287e320d/.github/workflows/monorepo-split.yml#L4

**Comment by yoriiis** [comment]
> Is your workflow using `uses: danharrin/monorepo-split-github-action@v2.4.0`? The Docker image in your screenshot is owned by the previous owner and I do not have access to update it.
> 
> This is how I use the current version: https://github.com/filamentphp/filament/blob/b4f9bff4f0d4d52390de56982f73a06c287e320d/.github/workflows/monorepo-split.yml#L4

I use this project on GitLab pipelines, not GitHub Actions, which is why I use Docker Hub.

Is the latest version of the image available on a registry (GitHub or Docker)?

**Comment by danharrin** [comment]
No, I haven't published any images since I took over the package.

**Comment by yoriiis** [comment]
> No, I haven't published any images since I took over the package.

Could we publish the image on the GitHub registry of this project?

**Comment by danharrin** [comment]
If you submit a PR for the new GitHub action to do that, I will review, add my credentials, and make a new release.

I think this specific issue is resolved though.
